-- Script de Criação do Banco de Dados Principal (SUPABASE / POSTGRESQL)

-- 1. Criação da Tabela de Notícias (Posts)
CREATE TABLE IF NOT EXISTS public.posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  subtitle TEXT,
  content TEXT NOT NULL,
  image TEXT,
  category TEXT,
  tags TEXT,
  source TEXT,
  slug TEXT UNIQUE NOT NULL,
  views INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Habilitar a Segurança em Nível de Linha (RLS - Row Level Security)
-- Isso é exigido pelo Supabase para segurança básica.
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;

-- 3. Políticas de Acesso (Policies)

-- A. Leitura: O seu site de notícias precisa ler publicamente as notícias para exibi-las aos visitantes
DROP POLICY IF EXISTS "Leitura Pública de Notícias" ON public.posts;
CREATE POLICY "Leitura Pública de Notícias"
  ON public.posts
  FOR SELECT
  USING (true);

-- B. Inserção: Permite que o seu sistema administrativo/gerador (webhook) crie notícias reais em seu banco.
DROP POLICY IF EXISTS "Inserção de Notícias via Webhook API" ON public.posts;
CREATE POLICY "Inserção de Notícias via Webhook API"
  ON public.posts
  FOR INSERT
  WITH CHECK (true);

-- C. Atualização: Permite editar publicações.
DROP POLICY IF EXISTS "Atualização de Notícias" ON public.posts;
CREATE POLICY "Atualização de Notícias"
  ON public.posts
  FOR UPDATE
  USING (true);

-- D. Exclusão: Permite que você também delete posts por meio da integração.
DROP POLICY IF EXISTS "Exclusões de Notícias" ON public.posts;
CREATE POLICY "Exclusões de Notícias"
  ON public.posts
  FOR DELETE
  USING (true);

-- 4. Função Opcional e Triggers para Gerar SLUGS se você for usar o painel nativo do Supabase.
-- Como seu painel em Node.js já gera o slug, a coluna 'slug' apenas recebe o texto. 

-- 5. Criar View e Índices (Opcionais) para Melhoria de Performance nas Buscas de Texto 
CREATE INDEX IF NOT EXISTS posts_search_idx ON public.posts USING GIN (to_tsvector('portuguese', title || ' ' || content));
CREATE INDEX IF NOT EXISTS posts_slug_idx ON public.posts (slug);
CREATE INDEX IF NOT EXISTS posts_category_idx ON public.posts (category);
